### ISSUE TITLE
Tesseract Not Found

### ISSUE THREAD

**Issue by Xyqc** [Stelath/wordscapes-bot#3]
The error:

``Traceback (most recent call last):
  File "C:\Users\yan5296\AppData\Local\Programs\Python\Python310\lib\site-packages\pytesseract\pytesseract.py", line 255, in run_tesseract
    proc = subprocess.Popen(cmd_args, **subprocess_args())
  File "C:\Users\yan5296\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\yan5296\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1440, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\yan5296\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\yan5296\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\yan5296\AppData\Local\Programs\Python\Python310\lib\site-packages\wordscapesbot\__main__.py", line 114, in <module>
    main()
  File "C:\Users\yan5296\AppData\Local\Programs\Python\Python310\lib\site-packages\wordscapesbot\__main__.py", line 110, in main
    wordscapes_bot.run()
  File "C:\Users\yan5296\AppData\Local\Programs\Python\Python310\lib\site-packages\wordscapesbot\wordscapes_bot.py", line 44, in run
    characters = ocr_characters(screenshot)
  File "C:\Users\yan5296\AppData\Local\Programs\Python\Python310\lib\site-packages\wordscapesbot\wordscapes_ocr\ocr.py", line 41, in ocr_characters
    character_string = pytesseract.image_to_string(resized_image, lang='eng', config='--psm 10')[0:1]
  File "C:\Users\yan5296\AppData\Local\Programs\Python\Python310\lib\site-packages\pytesseract\pytesseract.py", line 423, in image_to_string
    return {
  File "C:\Users\yan5296\AppData\Local\Programs\Python\Python310\lib\site-packages\pytesseract\pytesseract.py", line 426, in <lambda>
    Output.STRING: lambda: run_and_get_output(*args),
  File "C:\Users\yan5296\AppData\Local\Programs\Python\Python310\lib\site-packages\pytesseract\pytesseract.py", line 288, in run_and_get_output
    run_tesseract(**kwargs)
  File "C:\Users\yan5296\AppData\Local\Programs\Python\Python310\lib\site-packages\pytesseract\pytesseract.py", line 260, in run_tesseract
    raise TesseractNotFoundError()
pytesseract.pytesseract.TesseractNotFoundError: tesseract is not installed or it's not in your PATH. See README file for more information.``

I installed pytesseract using the terminal and Tesseract from the Github. How do I fix it?

**Comment by Xyqc** [comment]
I found the solution, follow this article if you are having issues: https://medium.com/@BH_Chinmay/installation-of-tesseract-in-python-77daf712420f
